import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { Waypoint } from 'react-waypoint';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { PersonalHeader } from '../components/personal-theme-header';
import Image from 'next/image'; // Importation de Image
import {
    MorePostsByPublicationDocument,
    MorePostsByPublicationQuery,
    MorePostsByPublicationQueryVariables,
    PageInfoFragment,
    PostFragment,
    PostsByPublicationDocument,
    PostsByPublicationQuery,
    PostsByPublicationQueryVariables,
    PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;
const HOSTNAME = process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST; // Variable pour le hostname
const STATIC_PAGE_SLUG = process.env.NEXT_PUBLIC_STATIC_PAGE_SLUG || ""; // Slug de la page statique

// Définir un type pour la réponse GraphQL des publications
interface StaticPageResponse {
    publication: {
        staticPage: {
            id: string;
            title: string;
            content: {
                html: string; // Ajout du sous-champ `html` pour le contenu
            };
        };
    };
}

type Props = {
    publication: PublicationFragment;
    page: {
        title: string;
        content: string;
    };
    initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, page, initialPageInfo }: Props) {
    const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
    const [loadedMore, setLoadedMore] = useState(false);

    // Ajouter les dépendances manquantes pour useEffect
    useEffect(() => {
        console.log('Page info updated:', pageInfo);
    }, [pageInfo]);

    const loadMore = async () => {
        try {
            const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
                GQL_ENDPOINT!,
                MorePostsByPublicationDocument,
                {
                    first: 20,
                    host: HOSTNAME!,
                    after: pageInfo.endCursor,
                },
            );

            if (!data.publication) {
                console.error("La publication n'a pas été trouvée lors du chargement de plus de posts.");
                return;
            }

            setPageInfo(data.publication.posts.pageInfo);
            setLoadedMore(true);
        } catch (error) {
            console.error("Erreur lors du chargement de plus de posts :", error);
        }
    };

    return (
        <AppProvider publication={publication}>
            <Layout>
                <Head>
                    <title>{page.title}</title>
                    <meta name="description" content="Page statique personnalisée" />
                    <meta property="twitter:card" content="summary_large_image" />
                    <meta property="twitter:title" content={page.title} />
                    <meta property="twitter:description" content="Page statique personnalisée" />
                    <meta
                        property="og:image"
                        content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
                    />
                    <meta
                        property="twitter:image"
                        content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
                    />
                    <script
                        type="application/ld+json"
                        dangerouslySetInnerHTML={{
                            __html: JSON.stringify(addPublicationJsonLd(publication)),
                        }}
                    />
                </Head>
                <Container className="mx-auto flex max-w-3xl flex-col items-stretch gap-10 px-5 py-10">
                    <PersonalHeader />
                    <div>
                        <h1 className="text-4xl font-bold mb-6">{page.title}</h1>
                        <div
                            className="prose lg:prose-xl"
                            dangerouslySetInnerHTML={{ __html: page.content }}
                        />
                    </div>
                    {!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
                        <button onClick={loadMore} className="bg-blue-500 text-white p-2 rounded">
                            Charger plus
                        </button>
                    )}
                    {loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
                        <Waypoint onEnter={loadMore} bottomOffset={'10%'} />
                    )}
                    <Footer />
                    {/* Exemple d'utilisation de <Image /> */}
                    <Image
                        src="/profile.jpg"
                        alt="Photo de profil"
                        width={300}
                        height={300}
                    />
                </Container>
            </Layout>
        </AppProvider>
    );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
    try {
        const publicationData = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
            GQL_ENDPOINT!,
            PostsByPublicationDocument,
            {
                first: 20,
                host: HOSTNAME!,
            },
        );

        if (!STATIC_PAGE_SLUG) {
            console.error("Le slug de la page statique (NEXT_PUBLIC_STATIC_PAGE_SLUG) n'est pas défini.");
            return {
                notFound: true,
            };
        }

        const staticPageQuery = `
            query {
                publication(host: "${HOSTNAME}") {
                    staticPage(slug: "${STATIC_PAGE_SLUG}") {
                        id
                        title
                        content {
                            html
                        }
                    }
                }
            }
        `;

        const staticPageData = await request<StaticPageResponse>(GQL_ENDPOINT!, staticPageQuery);

        if (!staticPageData.publication?.staticPage) {
            console.error("La page statique avec le slug spécifié n'a pas été trouvée.");
            return {
                notFound: true,
            };
        }

        const publication = publicationData.publication;
        if (!publication) {
            return {
                notFound: true,
            };
        }

        return {
            props: {
                publication,
                page: {
                    title: staticPageData.publication.staticPage.title,
                    content: staticPageData.publication.staticPage.content.html,
                },
                initialPageInfo: publication.posts.pageInfo,
            },
            revalidate: 1,
        };
    } catch (error) {
        console.error("Erreur lors de la récupération des données :", error);
        return {
            notFound: true,
        };
    }
};
